### ISSUE TITLE
[UX Enhancement] - Confirm before logging out. 

### ISSUE THREAD

**Issue by kishore-narendran** [prijindal/vitacademics-web#3]
I noticed that upon click of logout, it immediately logs out. It is preferred if you confirm a logout action to prevent any accidental clicks.

**Comment by prijindal** [comment]
Alright, I will put a modal or a dialog there

**Comment by prijindal** [comment]
Dialog Box for Logout: bd9d13b9e8467c697c855b36335b70bf106336ec
