### ISSUE TITLE
About Us and Version details requires Login

### ISSUE THREAD

**Issue by rahulkapoor90** [prijindal/vitacademics-web#7]
why is there a need to login to access about us and version details page, also feedback page needs screenshot upload feature.
and add tel:mobilenumber to advisor page just as you did mailto: mail ID.

**Comment by prijindal** [comment]
Actually its loading all the data of About and Version details once the user press Login, so there is no point allowing access to these pages without any data. Ofcourse we can allow feedback page for now.

**Comment by rahulkapoor90** [comment]
Okay.
